apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-attach-by-pod-and-container
  annotations:
    policies.kyverno.io/title: Block Pod Attach by Pod and Container
    policies.kyverno.io/category: Sample
    policies.kyverno.io/minversion: 1.4.2
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
     Block attach  
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: deny-exec
    match:
      resources:
        kinds:
        - PodAttachOptions
    preconditions:
      all:
      - key: {{ printf "{{ request.operation || 'BACKGROUND' }}" | quote }}
        operator: Equals
        value: CONNECT
    validate:
      message: deny-attach-by-pod-and-container
      deny:
        conditions:
          all:
          - key: {{ printf "{{ request.object.container }}" | quote }}
            operator: Equals
            value: "?*"

